remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
title: "Wajid Hussain"
subtitle: "Bridging Bits and Volts: From Power Systems to Data Streams"
name: "Wajid Hussain"
description: "Wajid Hussain's professional portfolio showcasing expertise in Electrical Engineering, IoT, and Data Science."
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: # the subpath of your site, e.g. "/blog"
repository: "wajidengg/wajidengg.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
logo: ""
masthead_title: " " # Removes the site title from the masthead

# Site Author
author:
  name: "Wajid Hussain"
  avatar: "/assets/img/headshot_circle.png"
  bio: "Electrical Engineer transitioning to IoT and Data Science"
  location: "Toronto, Canada"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://wajidengg.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wajidengg"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/whussain"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wajidengg"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/whussain"

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Exclude from processing
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
